"""
Name: Rachel Warner
Date: 11/30/2020
Program Name: Generator Modify
Program Purpose: Create a program that takes input from txt files to
                 generate a random sentence.
Inputs: txt files for articles, nouns, verbs, and prepositions
output: a random sentence generated by selecting random elements from the list created by the get_words function
"""

import random


def get_words(path):
    # Builds and returns a list of words for each file input
    with open(path) as f:
        line = f.read()
        selections = line.split()
        return selections

# Set variables for each part of the sentence, runs the get_words function and prompts the user
# for a file for input
articles = get_words(input("Please enter a file name for articles: "))
nouns = get_words(input("Please enter a file name for nouns: "))
verbs = get_words(input("Please enter a file name for verbs: "))
prepositions = get_words(input("Please enter a file name for prepositions: "))


def sentence():
    # Builds and returns a sentence
    return noun_phrase() + " " + verb_phrase()


def noun_phrase():
    # Builds and returns a noun phrase
    return random.choice(articles) + " " + random.choice(nouns)


def verb_phrase():
    # Builds and returns a verb phrase
    return random.choice(verbs) + " " + noun_phrase() + " " + prepositional_phrase()


def prepositional_phrase():
    # Builds and returns a prepositional phase
    return random.choice(prepositions) + " " + noun_phrase()


def main():
    number = int(input("Please enter the amount of sentences you would like to have: "))
    for count in range(number):
        print(sentence())


# Entry point for program execution
if __name__ == "__main__":
    main()
